/*write a program to print the two dimensional table of square root, to provide the 
square root of any number from 0 to 9.9.
row1,col1 |col2 | col3 | ....
number    |0.0  | 0.1  | ....
------------------------------
0.0|      |       |     |....      
1.0|      |       |     |....
2.0|      |       |     |....     
....*/